services:
  # reverse proxy (for production)
  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      # https
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=lohkianfeng@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # redirect http to https
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80" # http
      - "443:443" # https
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt # https

  # frontend (for production)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:v1
    container_name: client
    # ports: # for local dev
    #   - "3000:80"
    restart: unless-stopped
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    labels: # for traefik
      - "traefik.http.routers.client-router.rule=Host(`localhost`)" # dev
      - "traefik.http.routers.client-router.rule=Host(`kianfeng.com`)" # prod
      # https
      - "traefik.enable=true"
      - "traefik.http.routers.client-router.entryPoints=websecure"
      - "traefik.http.routers.client-router.tls.certResolver=myresolver"
    depends_on:
      - server

  # backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:v1
    container_name: server
    # ports: # for local dev
    #   - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env
      - ./server/.env
    labels: # for traefik
      - "traefik.http.routers.server-router.rule=(Host(`localhost`) && PathPrefix(`/api`))" # dev
      - "traefik.http.routers.server-router.rule=(Host(`kianfeng.com`) && PathPrefix(`/api`))" # prod
      # https
      - "traefik.enable=true"
      - "traefik.http.routers.server-router.entryPoints=websecure"
      - "traefik.http.routers.server-router.tls.certResolver=myresolver"
